Реализация системы рейгинта у аниме или манги.
anime-team-pet-projects/anime-summer pull request #14
Opened 2022-09-16 10:35 UTC by Cxatek18

Добавленно приложение:
   - rating
Добавленые модели:
  - Rating
Логика добавления рейтинга реализована как класс Mixin который наследуется и добавляет функионал.

2022-09-16 11:26 UTC, s1veme requested changes

2022-09-16 11:26 UTC, s1veme commented on rating/api/views.py
> +                {"ERROR": "have you done this before"}, status=status.HTTP_400_BAD_REQUEST
Ранее ты писал ключ `error` в lower-case, а сейчас в upper, почему здесь большими буквами?

2022-09-16 11:26 UTC, s1veme commented on rating/api/views.py
> +        if len(Rating.objects.filter(appraiser=appraiser, object_id=content_id, content_type=model_for_rating)) >= 1:
`len(Rating.objects.filter(appraiser=appraiser, object_id=content_id, content_type=model_for_rating))`

Есть метод `count`, который подсчитает кол-во объектов. 
Пример:
`Entry.objects.filter(headline__contains='Lennon').count()`

2022-09-16 11:26 UTC, s1veme commented on rating/api/views.py
> +        model.average_rating = round(avg_rating["estimation__avg"], 1)
Что за поле `average_rating ` и где я могу его посмотреть?

2022-09-16 11:26 UTC, s1veme commented on rating/api/views.py
> +            {"Status": "OK"}, status=status.HTTP_201_CREATED
Создал объект - верни его данные.

2022-09-16 11:26 UTC, s1veme commented on rating/api/views.py
> +    def сalculation_average_score(self, ratings_model):
Это лучше вынести в отдельный класс. Думаю, это не должно лежать во view.

2022-09-16 11:26 UTC, s1veme commented on rating/models.py
> +        'users.User', on_delete=models.CASCADE,
Используй метод `get_user_model` вместо `users.User`. 

См. https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#referencing-the-user-model

2022-09-16 12:11 UTC, Cxatek18 commented on rating/api/views.py
> +        model.average_rating = round(avg_rating["estimation__avg"], 1)
@s1veme добавил этот параметр в serializers(anime/api/serializers). И как раз при выводе деталей об Аниме мы будем видеть его среднее значение рейтинга.

2022-09-16 14:37 UTC, s1veme requested changes

2022-09-16 14:37 UTC, s1veme commented on rating/api/rating_services/rating_worker.py
> +class RatingWorker:
Может быть назвать этот файл `service.py`, а класс `RatingCalculation`?

2022-09-16 14:37 UTC, s1veme commented on rating/api/views.py
> +                {"error": "have you done this before."}, status=status.HTTP_400_BAD_REQUEST
Давай лучше уберём точку из ошибки?

2022-09-16 14:37 UTC, s1veme commented on rating/api/views.py
> +            ).data, status=status.HTTP_200_OK
Статус всё ещё должен быть 201.

2022-09-16 15:50 UTC, s1veme commented on rating/api/views.py
> +        model.average_rating = round(avg_rating["estimation__avg"], 1)
Тогда может лучше вычислять этот параметр в serializer'e? Что думаешь насчёт этого?
@Cxatek18

2022-10-01 07:03 UTC, s1veme requested changes

2022-10-01 07:03 UTC, s1veme commented on rating/api/views.py
> +        if rating_user:
Снова, длинный `if`. 

Можно сделать проще:
```
if not rating_user:
    return ...
rating_user.delete()
ratings_model = Rating.objects.filter(object_id=content_id)
...
```

2022-10-01 07:03 UTC, s1veme commented on rating/api/views.py
> +            if avg_rating is False:
Минусы `is` с `boolean`:
https://stackoverflow.com/questions/4591125/is-it-safe-to-replace-with-is-to-compare-boolean-values

2022-10-01 07:03 UTC, s1veme commented on rating/api/views.py
> +                {"result": "Deleted"}
Где-то тело `Response` с большой буквы, а где-то с маленькой. Откуда такое деление?

2022-10-01 07:03 UTC, s1veme commented on rating/models.py
> +        return str(f'{self.appraiser} {self.object_id} {self.id}')
`f'{self.appraiser} {self.object_id} {self.id}' == str(f'{self.appraiser} {self.object_id} {self.id}')`

Для чего это дополнительно оборачивать в `str`?

2022-10-01 12:42 UTC, s1veme commented on rating/api/views.py
> +                rating_user, context={"request": request}
Не совсем понимаю, для чего нам `context` в данном serializer'e?

2022-10-03 05:18 UTC, s1veme approved these changes

2022-10-06 10:12 UTC, merged