Implemented functionality - adding comments, outputting comments, ver…
anime-team-pet-projects/anime-summer pull request #5
Opened 2022-09-07 16:05 UTC by Cxatek18

…sion - 0.0.1

2022-09-08 13:53 UTC, s1veme requested changes

2022-09-08 13:53 UTC, s1veme commented on comments/api/views.py
> +class CommentView(viewsets.ViewSet):
Почему бы не использовать `ModelViewSet`, а не `ViewSet`?

2022-09-08 13:53 UTC, s1veme commented on comments/api/views.py
> +    @permission_classes([IsAuthenticated])
Можно сделать `permission_classes = [IsAuthenticated]`. Тогда не придётся везде писать декораторы.

2022-09-08 13:53 UTC, s1veme commented on comments/api/views.py
> +    def create(self, request, *args, **kwargs):
Такое ощущение, что комментарии должны создаваться в `AnimeModelViewSet`, можешь попробуешь реализовать этот вариант?

2022-09-08 13:53 UTC, s1veme commented on comments/api/views.py
> +        try:
`try/except` здесь не нужен, также ты не указал какую именно ошибку ты обрабатываешь. Так делать не стоит.

2022-09-08 13:53 UTC, s1veme commented on comments/api/views.py
> +                "error": "error"
Непонятно какая именно ошибка. Если будет какая-то ошибка, то Django самостоятельно даст об этом знать. Я не обрабатываю такие случаи.

2022-09-09 10:58 UTC, Cxatek18 commented on comments/api/views.py
> +    def create(self, request, *args, **kwargs):
Пришёл вот к такому варианту. Хотелось бы от вас (@s1veme ) услышать feedback.
```python
class CommentCreate:

    def defining_content_type(self, type_content):
        types_content = {
            'anime': Anime,
        }
        if type_content in types_content.keys():
            return types_content[type_content]
        else:
            raise BadRequest

    def create(self, request, *args, **kwargs):
        try:
            author = request.user
            content_id = request.data.get('content_id')
            type_content = request.data.get('type_content')
            content = ContentType.objects.get_for_model(
                self.defining_content_type(type_content)
            )
            text = request.data.get('text_comment')
            if request.data.get('parent'):
                parent = request.data.get('parent')
                parent_comment = Comment.objects.get(id=int(parent))
                Comment.objects.create(
                    parent=parent_comment, text_comment=text, author=author,
                    content_type=content, object_id=content_id,
                )
            else:
                Comment.objects.create(
                    text_comment=text, author=author,
                    content_type=content, object_id=content_id,
                )
            return Response({
                "Comment created": "ok"
            }, status=status.HTTP_201_CREATED)
        except BadRequest:
            return Response({
                "error": "error"
            }, status=status.HTTP_400_BAD_REQUEST)
``` 
И так же добавленно наследование этого класса.
```python
class CommentView(CommentCreate, viewsets.ModelViewSet)
```

2022-09-09 13:09 UTC, s1veme commented on anime/api/urls.py
> +    path('add-comment/', AnimeModelViewSet.as_view({'post': 'create'}))
Вынеси это в отдельный `action` в `ModelViewSet`, так же, как и методы `update`, `list`, `destroy`.

2022-09-09 13:10 UTC, s1veme commented on comments/api/views.py
> +class CommentView(viewsets.ModelViewSet):
`CommentView`, я полагаю, что здесь больше не нужен.

2022-09-09 13:15 UTC, s1veme requested changes

2022-09-09 13:15 UTC, s1veme commented on comments/api/views.py
> +        anime = ContentType.objects.get_for_model(self.queryset.model)
Почему переменная называется `anime`?

Может быть её лучше назвать `model_for_comment`, либо что-нибудь в таком стиле?

2022-09-09 13:15 UTC, s1veme commented on comments/api/views.py
> +            "Comment created": "ok"
Лучше вернуть данные комментария, который был только что создан.

2022-09-09 13:15 UTC, s1veme commented on comments/api/views.py
> +            parent = request.data.get('parent')
Ты два раза делаешь `get`. Можно обойтись и одним. Например:
```
parent = request.data.get('parent')
if parent:
    ...
```

2022-09-10 05:28 UTC, Cxatek18 commented on anime/api/urls.py
> +    path('add-comment/', AnimeModelViewSet.as_view({'post': 'create'}))
```python
@action(detail=True, methods=['post'], url_path='add-comment/')
    def create(self, request, *args, **kwargs):
        author = request.user
        content_id = request.data.get('content_id')
        anime = ContentType.objects.get_for_model(self.queryset.model)
        text = request.data.get('text_comment')
        if request.data.get('parent'):
            parent = request.data.get('parent')
            parent_comment = Comment.objects.get(id=int(parent))
            Comment.objects.create(
                parent=parent_comment, text_comment=text, author=author,
                content_type=anime, object_id=content_id,
            )
        else:
            Comment.objects.create(
                text_comment=text, author=author,
                content_type=anime, object_id=content_id,
            )
        return Response({
            "Comment created": "ok"
        }, status=status.HTTP_201_CREATED)
```
@s1veme вот так предлагаете реализовать?

2022-09-10 05:51 UTC, Cxatek18 commented on comments/api/views.py
> +            "Comment created": "ok"
Может быть возвращать все коментарии чтоб сразу подгружать изменения на Frontend?

2022-09-10 10:06 UTC, s1veme commented on comments/api/views.py
> +            "Comment created": "ok"
> Может быть возвращать все коментарии чтоб сразу подгружать изменения на Frontend?

Не стоит. Просто верни данные созданного комментария.

2022-09-10 10:07 UTC, s1veme commented on anime/api/urls.py
> +    path('add-comment/', AnimeModelViewSet.as_view({'post': 'create'}))
> ```python
> @action(detail=True, methods=['post'], url_path='add-comment/')
>     def create(self, request, *args, **kwargs):
>         author = request.user
>         content_id = request.data.get('content_id')
>         anime = ContentType.objects.get_for_model(self.queryset.model)
>         text = request.data.get('text_comment')
>         if request.data.get('parent'):
>             parent = request.data.get('parent')
>             parent_comment = Comment.objects.get(id=int(parent))
>             Comment.objects.create(
>                 parent=parent_comment, text_comment=text, author=author,
>                 content_type=anime, object_id=content_id,
>             )
>         else:
>             Comment.objects.create(
>                 text_comment=text, author=author,
>                 content_type=anime, object_id=content_id,
>             )
>         return Response({
>             "Comment created": "ok"
>         }, status=status.HTTP_201_CREATED)
> ```
> 
> @s1veme вот так предлагаете реализовать? Если да, то я так полагаю надо сделать и с list, update, destroy. И убрать view под названием CommentView. В таком случае получиться один view который мы сможем наследовать.

Да, всё верно. 
Только `url_path` должен быть `comments`, просто будет меняться тип запроса.

2022-09-10 10:42 UTC, s1veme requested changes

2022-09-10 10:42 UTC, s1veme commented on comments/api/views.py
> +class CommentView:
`CommentView` переименовать в `CommentMixin`.

2022-09-10 10:42 UTC, s1veme commented on comments/api/views.py
> +    @action(detail=False, methods=['post'], url_path='add-comment')
Вместо `add-comment`, `list-comment` и так далее...
Лучше сделать просто `comment` и менять тип запроса. 

Например, `update-comment` можно заменить на `comment` с `methods=['PUT', 'PATCH']`.

2022-09-10 10:42 UTC, s1veme commented on comments/api/views.py
>          if not Comment.objects.filter(author=request.user.id, id=pk).exists():
Видишь одни и те же строчки в каждом методе? 

Нужно это вынести в отдельную функцию/метод, либо поработать с permissions. 
Второй вариант будет получше, я думаю.

2022-09-11 06:57 UTC, s1veme approved these changes

2022-09-11 13:29 UTC, merged